# automations.yaml
automation:
  - alias: "notification_brief_morning"
    id: "notification_brief_morning"
    description: "Trigger brief in the morning"
    trigger:
      - platform: time
        at: "06:30:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: script.turn_on
        target:
          entity_id: script.daily_brief

  - alias: "notification_brief_evening"
    id: "notification_brief_evening"
    description: "Trigger brief in the evening"
    trigger:
      - platform: time
        at: "17:30:00"
    action:
      - service: script.turn_on
        target:
          entity_id: script.daily_brief
