# Base brief package configuration

input_text:
  work_location:
    name: "Work Location"
    initial: "" # Set your work address here

# Sensors for context awareness
binary_sensor:
  - platform: template
    sensors:
      morning_commute_time:
        unique_id: morning_commute_time
        value_template: >
          {{ now().weekday() < 5 and 
             now().hour >= 6 and 
             now().hour < 9 }}

      evening_time:
        unique_id: evening_time
        value_template: >
          {{ now().hour >= 17 and now().hour < 23 }}
