
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
packages: !include_dir_named: packages/

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.86.2

google_assistant:
  project_id: homeassistant-32654
  service_account: !include SERVICE_ACCOUNT.json
  report_state: true

# Custom Configs Below
recorder: !include recorder.yaml

notify:
  - platform: group
    name: all_mobile_devices
    services:
      - service: mobile_app_pixel_6_pro
      - service: mobile_app_pixel_7_pro

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code_arm_required: false