- alias: Brian Remote Good Night
  triggers:
    - trigger: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: 7208c07c752cc38fd6b147f38261f829
        label: Scene 001
        value: KeyPressed
  actions:
    - action: input_boolean.turn_on
      entity_id: input_boolean.good_night
  mode: single

- alias: Brian Bedside On
  triggers:
    - trigger: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: 7208c07c752cc38fd6b147f38261f829
        label: Scene 004
        value: KeyPressed
  actions:
    - action: light.turn_on
      entity_id: light.brian_s_table_lamp
  mode: single

- alias: Brian Bedside Off
  triggers:
    - trigger: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: 7208c07c752cc38fd6b147f38261f829
        label: Scene 003
        value: KeyPressed
  actions:
    - action: light.turn_off
      entity_id: light.brian_s_table_lamp
  mode: single

- alias: Brian Bedside Full Brightness
  triggers:
    - trigger: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: 720c07c752cc38fd6b147f38261f829
        label: Scene 004
        value: KeyPressedx2
  actions:
    - action: light.turn_on
      entity_id: light.brian_s_table_lamp
      data:
        brightness_pct: 100
  mode: single
