- alias: Brian Remote Good Night
  triggers:
    - trigger: event
      event_type: zwave_js_value_notification
      event_data:
        device_id: 7208c07c752cc38fd6b147f38261f829
        label: Scene 001
        value: KeyPressed
  actions:
    - action: input_boolean.turn_on
      entity_id: input_boolean.good_night
  mode: single
