# - alias: "Good Night Trigger"
#   trigger:
#     - platform: state
#       entity_id: input_boolean.good_night
#       to: "on"
#       from: "off"
#   condition:
#     - condition: state
#       entity_id: sun.sun
#       state: "below_horizon"
#     - condition: state
#       entity_id: input_boolean.guest_mode
#       state: "off"
#   action:
#     - service: input_boolean.turn_off
#       entity_id: input_boolean.good_night
#     - service: homeassistant.turn_off
#       entity_id:
#         - light.downstairs_lights
#         - light.outside_lights
#         - remote.living_room_tv
#         - remote.master_bedroom_tv
#         - light.holiday_lights
#     - service: input_boolean.turn_on
#       entity_id: input_boolean.camera_notifications
#     - service: lock.lock
#       entity_id: lock.front_door
#     - service: media_player.turn_off
#       entity_id:
#         - media_player.kitchen_display
#         - media_player.living_room_speaker

- alias: "Good Night Trigger"
  trigger:
    - platform: state
      entity_id: input_boolean.good_night
      to: "on"
      from: "off"
  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    # First turn off the good night switch regardless of conditions
    - service: input_boolean.turn_off
      entity_id: input_boolean.good_night

    # Check dishwasher state and handle accordingly
    - choose:
        # If dishwasher is running, perform all normal actions
        - conditions:
            - condition: state
              entity_id: sensor.dishwasher_state
              state: "BSH.Common.EnumType.OperationState.Run"
          sequence:
            - service: homeassistant.turn_off
              entity_id:
                - light.downstairs_lights
                - light.outside_lights
                - remote.living_room_tv
                - remote.master_bedroom_tv
                - light.holiday_lights
            - service: input_boolean.turn_on
              entity_id: input_boolean.camera_notifications
            - service: lock.lock
              entity_id: lock.front_door
            - service: media_player.turn_off
              entity_id:
                - media_player.kitchen_display
                - media_player.living_room_speaker
                - media_player.music_room_speaker

      # If dishwasher is not running
      default:
        # Turn off everything except downstairs lights
        - service: homeassistant.turn_off
          entity_id:
            - light.outside_lights
            - remote.living_room_tv
            - remote.master_bedroom_tv
            - light.holiday_lights
        - service: input_boolean.turn_on
          entity_id: input_boolean.camera_notifications
        - service: lock.lock
          entity_id: lock.front_door
        - service: media_player.turn_off
          entity_id:
            - media_player.kitchen_display
            - media_player.living_room_speaker
            - media_player.music_room_speaker

        # Send actionable notification
        - service: notify.all_mobile_devices
          data:
            message: "Dishwasher is not running. Kitchen lights will stay on until dishwasher starts or you ignore this alert."
            data:
              actions:
                - action: "ignore"
                  title: "Ignore"

        # Wait for either ignore action or dishwasher to start
        - wait_for_trigger:
            - platform: event
              event_type: mobile_app_notification_action
              event_data:
                action: ignore
            - platform: state
              entity_id: sensor.dishwasher_state
              to: "BSH.Common.EnumType.OperationState.Run"
          continue_on_timeout: false

        # If dishwasher started, wait 2 minutes before turning off kitchen lights
        - choose:
            - conditions:
                - condition: state
                  entity_id: sensor.dishwasher_state
                  state: "BSH.Common.EnumType.OperationState.Run"
              sequence:
                - delay: "00:02:00"

        # Finally turn off kitchen lights
        - service: light.turn_off
          entity_id: light.downstairs_lights

- alias: "Back Up Nightly Lock"
  trigger:
    - platform: time
      at: "23:00:00"
  action:
    - service: lock.lock
      entity_id: lock.front_door
    - service: input_boolean.turn_on
      entity_id: input_boolean.camera_notifications
