- alias: "Good Night Trigger"
  trigger:
    - platform: state
      entity_id: input_boolean.good_night
      to: "on"
      from: "off"
  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    # First turn off the good night switch
    - service: input_boolean.turn_off
      entity_id: input_boolean.good_night

    # Common actions that always happen
    - service: light.turn_on
      entity_id:
        - light.brian_s_table_lamp
        - light.hester_s_table_lamp
      data:
        brightness_pct: 50
        transition: 3
    - service: homeassistant.turn_off
      entity_id:
        - light.outside_lights
        - remote.living_room_tv
        - remote.master_bedroom_tv
        #- light.holiday_lights
    - service: media_player.turn_off
      entity_id:
        - media_player.kitchen_display
        - media_player.living_room_speaker
        - media_player.music_room_speaker
    - service: alarm_control_panel.alarm_arm_night
      target:
        entity_id: alarm_control_panel.home_alarm
    # Check dishwasher state and handle accordingly
    - choose:
        # If dishwasher is running, turn off all lights and arm
        - conditions:
            - condition: state
              entity_id: sensor.dishwasher_state
              state: "BSH.Common.EnumType.OperationState.Run"
          sequence:
            - service: light.turn_off
              entity_id: light.downstairs_lights
            - service: alarm_control_panel.alarm_arm_home
              target:
                entity_id: alarm_control_panel.home_alarm

      # If dishwasher is not running
      default:
        # Send actionable notification
        - service: notify.all_mobile_devices
          data:
            message: "Dishwasher is not running. Kitchen lights will stay on until dishwasher starts or you ignore this alert."
            data:
              actions:
                - action: "ignore"
                  title: "Ignore"

        # Wait for either ignore action or dishwasher to start
        - wait_for_trigger:
            - platform: event
              event_type: mobile_app_notification_action
              event_data:
                action: ignore
            - platform: state
              entity_id: sensor.dishwasher_state
              to: "BSH.Common.EnumType.OperationState.Run"
          continue_on_timeout: false

        # If dishwasher started, wait 2 minutes
        - choose:
            - conditions:
                - condition: state
                  entity_id: sensor.dishwasher_state
                  state: "BSH.Common.EnumType.OperationState.Run"
              sequence:
                - delay: "00:02:00"

        # Finally turn off kitchen lights and arm system
        - service: light.turn_off
          entity_id: light.downstairs_lights
        - service: alarm_control_panel.alarm_arm_night
          target:
            entity_id: alarm_control_panel.home_alarm
