- alias: "Good Night Trigger"
  trigger:
    - platform: state
      entity_id: input_boolean.good_night
      to: "on"
      from: "off"
  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.good_night
    - service: homeassistant.turn_off
      entity_id:
        - light.main_floor_lights
        - light.outside_lights
        - remote.living_room_tv
        - remote.master_bedroom_tv
    - service: input_boolean.turn_on
      entity_id: input_boolean.camera_notifications
    - service: lock.lock
      entity_id: lock.front_door
    - service: media_player.turn_off
      entity_id:
        - media_player.kitchen_display
        - media_player.living_room_speaker
        - media_player.music_room_speaker

- alias: "Back Up Nightly Lock"
  trigger:
    - platform: time
      at: "23:00:00"
  action:
    - service: lock.lock
      entity_id: lock.front_door
    - service: input_boolean.turn_on
      entity_id: input_boolean.camera_notifications
