light:
  - platform: switch
    name: Outdoor Plug Light
    entity_id: switch.outdoor_plug
  - platform: switch
    name: Christmas Tree
    entity_id: switch.christmas_tree

automation:
  - alias: "Turn on the Holiday Lights at Dusk"
    trigger:
      - platform: state
        entity_id: sun.sun
        to: "below_horizon"
    action:
      - service: light.turn_on
        target:
          entity_id: light.holiday_lights
    mode: single
