alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code_arm_required: false
    arming_time: 10
    disarm_after_trigger: false

light:
  - platform: group
    name: After Dark Entry Lights
    entities:
      - light.front_yard_lights
      - light.hallway_entry
      - light.hallway_corridor

automation:
  - alias: "mode_morning_wake_detection"
    id: "mode_morning_wake_detection"
    description: "Transition ot home mode in morning"
    trigger:
      # Time-based trigger as backup
      - platform: time
        at: "08:00:00"
      # Light switches being turned on
      - platform: state
        entity_id:
          - light.hallway_entry
          - light.kitchen_counter_lights
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
      # Only trigger between 4am and 10am
      - condition: time
        after: "04:00:00"
        before: "10:00:00"
    action:
      - service: alarm_control_panel.alarm_arm_home
        target:
          entity_id: alarm_control_panel.home_alarm

  - alias: "presence_everyone_left"
    id: "presence_everyone_left"
    description: "Handle when everyone has left home"
    trigger:
      - platform: numeric_state
        entity_id: zone.home
        below: 1
        for:
          minutes: 1
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - service: alarm_control_panel.alarm_arm_away
        target:
          entity_id: alarm_control_panel.home_alarm
      - service: homeassistant.turn_off
        target:
          entity_id:
            - remote.living_room_tv
            - remote.master_bedroom_tv
            - media_player.kitchen_display
            - media_player.living_room_speaker
            - media_player.music_room_speaker
      - service: light.turn_off
        target:
          entity_id: all

  - alias: "presence_someone_returned"
    id: "presence_someone_returned"
    description: "Handle when someone returns home"
    trigger:
      - platform: numeric_state
        entity_id: zone.home
        above: 0
    action:
      - if:
          condition: state
          entity_id: alarm_control_panel.home_alarm
          state: "armed_away"
        then:
          - service: lock.unlock
            target:
              entity_id: lock.front_door
          - service: logbook.log
            data:
              name: "Front Door"
              message: "Door unlocked due to arrival when system is in away mode"
      - service: alarm_control_panel.alarm_arm_home
        target:
          entity_id: alarm_control_panel.home_alarm

  - alias: "alarm_handle_armed_away"
    id: "alarm_handle_armed_away"
    description: "Actions when alarm is armed away"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "armed_away"
    action:
      - service: input_boolean.turn_on
        target:
          entity_id:
            - input_boolean.camera_notifications_indoor
            - input_boolean.camera_notifications_outdoor
      - service: lock.lock
        target:
          entity_id: lock.front_door

  - alias: "alarm_handle_armed_night"
    id: "alarm_handle_armed_night"
    description: "Actions when alarm is armed night"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "armed_night"
    action:
      # Always turn on outdoor camera notifications
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.camera_notifications_outdoor
      # Only turn on indoor camera notifications if guest mode is OFF
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.guest_mode
                state: "off"
            sequence:
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.camera_notifications_indoor
      # Always lock the front door
      - service: lock.lock
        target:
          entity_id: lock.front_door

  - alias: "alarm_handle_armed_home"
    id: "alarm_handle_armed_home"
    description: "Actions when alarm is armed home"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "armed_home"
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.camera_notifications_outdoor
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.camera_notifications_indoor

  - alias: "light_welcome_home"
    id: "light_welcome_home"
    description: "Turn on entry lights on return"
    trigger:
      - platform: state
        entity_id: zone.home
    condition:
      - condition: template
        value_template: >
          {{ trigger.from_state.state | int < trigger.to_state.state | int }}
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
    action:
      - service: light.turn_on
        target:
          entity_id: light.after_dark_entry_lights
