alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code_arm_required: false
    arming_time: 10
    disarm_after_trigger: false

light:
  - platform: group
    name: After Dark Entry Lights
    entities:
      - light.front_yard_lights
      - light.hallway_entry
      - light.hallway_corridor

automation:
  - alias: "Morning Wake Detection"
    description: "Transitions from night mode to home mode when morning activity is detected"
    trigger:
      # Time-based trigger as backup
      - platform: time
        at: "08:00:00"
      # Light switches being turned on
      - platform: state
        entity_id:
          - light.hallway_entry
          - light.kitchen_counter_lights
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
      # Only trigger between 4am and 10am
      - condition: time
        after: "04:00:00"
        before: "10:00:00"
    action:
      - service: alarm_control_panel.alarm_arm_home
        target:
          entity_id: alarm_control_panel.home_alarm

  - alias: "Everyone Left"
    trigger:
      - platform: numeric_state
        entity_id: zone.home
        below: 1
        for:
          minutes: 1
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - service: alarm_control_panel.alarm_arm_away
        target:
          entity_id: alarm_control_panel.home_alarm

  - alias: "Someone Came Home"
    trigger:
      - platform: numeric_state
        entity_id: zone.home
        above: 0
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - service: alarm_control_panel.alarm_arm_home
        target:
          entity_id: alarm_control_panel.home_alarm

  - alias: "Handle Home Alarm Armed Away"
    description: "Secure house when alarm is armed away"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "armed_away"
    action:
      - service: homeassistant.turn_off
        target:
          entity_id:
            - remote.living_room_tv
            - remote.master_bedroom_tv
            - media_player.kitchen_display
            - media_player.living_room_speaker
            - media_player.music_room_speaker
      - service: light.turn_off
        target:
          entity_id: all
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.camera_notifications
      - service: lock.lock
        target:
          entity_id: lock.front_door

  - alias: "Handle Home Alarm Armed Night"
    description: "Secure house for night"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "armed_night"
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.camera_notifications
      - service: lock.lock
        target:
          entity_id: lock.front_door

  - alias: "Handle Home Alarm Armed Home"
    description: "Welcome actions when system set to armed home"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "armed_home"
    action:
      - service: lock.unlock
        target:
          entity_id: lock.front_door
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.camera_notifications

  - alias: "Welcome Home Light Control"
    description: "Turn on entry lights wehn someone arrives home after dark"
    trigger:
      - platform: state
        entity_id: zone.home
    condition:
      - condition: template
        value_template: >
          {{ trigger.from_state.state | int < trigger.to_state.state | int }}
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
    action:
      - service: light.turn_on
        target:
          entity_id: light.after_dark_entry_lights
