light:
  - platform: group
    name: After Dark Entry Lights
    entities:
      - light.front_yard_lights
      - light.hallway_entry
      - light.hallway_corridor

automation:
  - alias: "Everyone Left"
    trigger:
      - platform: numeric_state
        entity_id:
          - zone.home
        below: 1
        for:
          hours: 0
          minutes: 1
          seconds: 0
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.away_mode

  - alias: "Someone Came Home"
    trigger:
      - platform: numeric_state
        entity_id:
          - zone.home
        above: 0
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.away_mode

  - alias: "Turn on the lights and unlock the door when someone comes home"
    description: "Unlock door and control lights when away mode is turned off"
    trigger:
      - platform: state
        entity_id: input_boolean.away_mode
        from: "on"
        to: "off"
    condition: []
    action:
      - service: lock.unlock
        target:
          entity_id: lock.front_door
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
      - service: light.turn_on
        target:
          entity_id: light.after_dark_entry_lights
    mode: single

  - alias: "Secure the house if no one is home"
    trigger:
      platform: state
      entity_id: input_boolean.away_mode
      to: "on"
    action:
      - service: homeassistant.turn_off
        entity_id:
          - remote.living_room_tv
          - remote.master_bedroom_tv
          - media_player.kitchen_display
          - media_player.living_room_speaker
          - media_player.music_room_speaker
      - service: light.turn_off
        entity_id: all
      - service: input_boolean.turn_on
        entity_id: input_boolean.camera_notifications
      - service: lock.lock
        entity_id: lock.front_door
    mode: single
