# packages/remotes.yaml
input_boolean:
  brian_lamp_dimming:
    name: "Brian's Lamp Dimming Active"
    initial: false
  hester_lamp_dimming:
    name: "Hester's Lamp Dimming Active"
    initial: false

script:
  lamp_dim_sequence:
    variables:
      lamp: null
      direction: null # 'up' or 'down'
      dimming_helper: null
    mode: restart
    sequence:
      # Start by making sure helper is in correct state
      - service: input_boolean.turn_on
        data:
          entity_id: "{{ dimming_helper }}"

      # - repeat:
      #     while:
      #       - condition: template
      #         value_template: "{{ is_state(dimming_helper, 'on') }}"
      #     sequence:
      #       - choose:
      #           - conditions:
      #               - "{{ (direction == 'up' and state_attr(lamp, 'brightness') | default(0) >= 255) or
      #                 (direction == 'down' and state_attr(lamp, 'brightness') | default(0) <= 0) }}"
      #             sequence:
      #               - service: input_boolean.turn_off
      #                 data:
      #                   entity_id: "{{ dimming_helper }}"
      #               - stop: "Reached brightness limit"
      #
      #       - service: light.turn_on
      #         data:
      #           entity_id: "{{ lamp }}"
      #           brightness_step_pct: "{{ 10 if direction == 'up' else -10 }}"
      #           transition: 1
      #       - delay:
      #           seconds: 1

automation:
  - id: brian_remote
    alias: "Brian's Remote Control"
    use_blueprint:
      path: zwave_remote.yaml
      input:
        remote_device: 7208c07c752cc38fd6b147f38261f829
        scene_001_press:
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.good_night
        scene_004_press:
          - service: light.turn_on
            data:
              entity_id: light.brian_s_table_lamp
        scene_004_held:
          - service: script.lamp_dim_sequence
            data:
              lamp: light.brian_s_table_lamp
              direction: up
              dimming_helper: input_boolean.brian_lamp_dimming
        scene_004_released:
          - service: input_boolean.turn_off
            data:
              entity_id: input_boolean.brian_lamp_dimming
        scene_004_double:
          - service: light.turn_on
            data:
              entity_id: light.brian_s_table_lamp
              brightness_pct: 100
        scene_003_press:
          - service: light.turn_off
            data:
              entity_id: light.brian_s_table_lamp
        scene_003_held:
          - service: script.lamp_dim_sequence
            data:
              lamp: light.brian_s_table_lamp
              direction: down
              dimming_helper: input_boolean.brian_lamp_dimming
        scene_003_released:
          - service: input_boolean.turn_off
            data:
              entity_id: input_boolean.brian_lamp_dimming

  - id: hester_remote
    alias: "Hester's Remote Control"
    use_blueprint:
      path: zwave_remote.yaml
      input:
        remote_device: b9e908c896f44c782113acbaf0985571
        scene_001_press:
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.good_night
        scene_003_press:
          - service: light.turn_on
            data:
              entity_id: light.hester_s_table_lamp
        scene_003_held:
          - service: script.lamp_dim_sequence
            data:
              lamp: light.hester_s_table_lamp
              direction: up
              dimming_helper: input_boolean.hester_lamp_dimming
        scene_003_released:
          - service: input_boolean.turn_off
            data:
              entity_id: input_boolean.hester_lamp_dimming
        scene_004_press:
          - service: light.turn_off
            data:
              entity_id: light.hester_s_table_lamp
        scene_004_held:
          - service: script.lamp_dim_sequence
            data:
              lamp: light.hester_s_table_lamp
              direction: down
              dimming_helper: input_boolean.hester_lamp_dimming
        scene_004_released:
          - service: input_boolean.turn_off
            data:
              entity_id: input_boolean.hester_lamp_dimming
