# packages/security_lights.yaml

homeassistant:
  customize:
    input_boolean.front_lights_auto_off:
      hidden: true
    input_boolean.back_lights_auto_off:
      hidden: true
    input_boolean.doorbell_lights_auto_off:
      hidden: true
input_boolean:
  front_lights_auto_off:
    name: Front Lights Auto Off
    icon: mdi:lightbulb-auto
    initial: off

  back_lights_auto_off:
    name: Back Lights Auto Off
    icon: mdi:lightbulb-auto
    initial: off

  doorbell_lights_auto_off:
    name: Doorbell Lights Auto Off
    icon: mdi:lightbulb-auto
    initial: off

automation:
  - alias: "Security Lighting - Person Detection"
    description: "Manage outdoor lights based on person detection from any camera"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.front_drive_person_occupancy
          - binary_sensor.back_door_person_occupancy
          - binary_sensor.front_doorbell_person_occupancy
        to: "on"
    condition:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 0
      - condition: not
        conditions:
          - condition: state
            entity_id: alarm_control_panel.home_alarm
            state: "disarmed"
    action:
      # Set auto-off flags for any lights that are currently off
      - if:
          - condition: state
            entity_id: light.front_yard_lights
            state: "off"
        then:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.front_lights_auto_off
      - if:
          - condition: state
            entity_id: light.back_yard
            state: "off"
        then:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.back_lights_auto_off
      - if:
          - condition: or
            conditions:
              - condition: state
                entity_id: select.front_doorbell_security_light
                state: "Off"
              - condition: state
                entity_id: light.front_doorbell_ring_light
                state: "off"
        then:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.doorbell_lights_auto_off

      # Turn on all lights
      - service: light.turn_on
        target:
          entity_id:
            - light.front_yard_lights
            - light.back_yard
      - service: select.select_option
        data:
          option: "On"
        target:
          entity_id: select.front_doorbell_security_light
      - service: light.turn_on
        target:
          entity_id: light.front_doorbell_ring_light

      # wait 10 minutes
      - delay: "00:10:00"

      # Turn off each light group if it was originally off
      - if:
          - condition: state
            entity_id: input_boolean.front_lights_auto_off
            state: "on"
        then:
          - service: light.turn_off
            target:
              entity_id: light.front_yard_lights
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.front_lights_auto_off

      - if:
          - condition: state
            entity_id: input_boolean.back_lights_auto_off
            state: "on"
        then:
          - service: light.turn_off
            target:
              entity_id: light.back_yard
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.back_lights_auto_off

      - if:
          - condition: state
            entity_id: input_boolean.doorbell_lights_auto_off
            state: "on"
        then:
          - service: select.select_option
            data:
              option: "Off"
            target:
              entity_id: select.front_doorbell_security_light
          - service: light.turn_off
            target:
              entity_id: light.front_doorbell_ring_light
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.doorbell_lights_auto_off
    mode: restart
