# packages/towner_notifications.yaml
#
# Reliable Towner school notifications with state-based tracking
# - Morning departure: 30s verification delay, sets school arrival expectation
# - School arrival: only notifies if expected, clears expectation
# - School departure: 30s verification delay, sets home arrival expectation
# - Home arrival: only notifies if expected, clears expectation
# - Timeouts: expectations auto-clear after 30 minutes
# - Overdue alerts: notifications if 20+ minutes late

input_boolean:
  towner_expecting_school_arrival:
    name: "Expecting Towner at School"
    icon: mdi:school
    initial: false
  towner_expecting_home_arrival:
    name: "Expecting Towner Home from School"
    icon: mdi:home
    initial: false

automation:
  - id: "towner_left_home_verification"
    alias: "Towner: Verify departure from home"
    description: "Wait 30 seconds to verify Towner actually left home, then set school expectation"
    trigger:
      - platform: state
        entity_id: person.towner
        from: "home"
    condition:
      - condition: time
        after: "06:30:00"
        before: "09:00:00"
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.towner_expecting_school_arrival
        state: "off"
    action:
      - delay: "00:00:30"
      - condition: template
        value_template: "{{ states('person.towner') != 'home' }}"
      - service: notify.all_mobile_devices
        data:
          title: "Towner — Left for School"
          message: "Towner left home for school at {{ now().strftime('%-I:%M %p') }}."
          data:
            tag: "towner-school"
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.towner_expecting_school_arrival
    mode: single

  - id: "towner_arrived_school"
    alias: "Towner: Arrived at school"
    description: "Notify when Towner arrives at school (only if expected)"
    trigger:
      - platform: state
        entity_id: person.towner
        to: "La Vista Middle School"
    condition:
      - condition: state
        entity_id: input_boolean.towner_expecting_school_arrival
        state: "on"
    action:
      - service: notify.all_mobile_devices
        data:
          title: "Towner — Arrived at School"
          message: "Towner arrived at La Vista Middle School at {{ now().strftime('%-I:%M %p') }}."
          data:
            tag: "towner-school"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.towner_expecting_school_arrival
    mode: single

  - id: "towner_left_school_verification"
    alias: "Towner: Verify departure from school"
    description: "Wait 30 seconds to verify Towner actually left school, then set home expectation"
    trigger:
      - platform: state
        entity_id: person.towner
        from: "La Vista Middle School"
    condition:
      - condition: state
        entity_id: input_boolean.towner_expecting_home_arrival
        state: "off"
    action:
      - delay: "00:00:30"
      - condition: template
        value_template: "{{ states('person.towner') != 'La Vista Middle School' }}"
      - service: notify.all_mobile_devices
        data:
          title: "Towner — Left School"
          message: "Towner left La Vista Middle School at {{ now().strftime('%-I:%M %p') }}."
          data:
            tag: "towner-school"
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.towner_expecting_home_arrival
    mode: single

  - id: "towner_arrived_home"
    alias: "Towner: Arrived home from school"
    description: "Notify when Towner arrives home (only if expected)"
    trigger:
      - platform: state
        entity_id: person.towner
        to: "home"
    condition:
      - condition: state
        entity_id: input_boolean.towner_expecting_home_arrival
        state: "on"
    action:
      - service: notify.all_mobile_devices
        data:
          title: "Towner — Home from School"
          message: "Towner arrived home from school at {{ now().strftime('%-I:%M %p') }}."
          data:
            tag: "towner-school"
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.towner_expecting_home_arrival
    mode: single

  - id: "towner_school_expectation_timeout"
    alias: "Towner: School arrival timeout"
    description: "Clear school expectation after 30 minutes"
    trigger:
      - platform: state
        entity_id: input_boolean.towner_expecting_school_arrival
        to: "on"
        for: "00:30:00"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.towner_expecting_school_arrival
    mode: single

  - id: "towner_home_expectation_timeout"
    alias: "Towner: Home arrival timeout"
    description: "Clear home expectation after 30 minutes"
    trigger:
      - platform: state
        entity_id: input_boolean.towner_expecting_home_arrival
        to: "on"
        for: "00:30:00"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.towner_expecting_home_arrival
    mode: single

  - id: "towner_school_arrival_overdue"
    alias: "Towner: School arrival overdue warning"
    description: "Warn if Towner hasn't arrived at school within 20 minutes"
    trigger:
      - platform: state
        entity_id: input_boolean.towner_expecting_school_arrival
        to: "on"
        for: "00:20:00"
    action:
      - service: notify.all_mobile_devices
        data:
          title: "Towner — School Arrival Overdue"
          message: "Towner left for school 20+ minutes ago but hasn't arrived yet."
          data:
            tag: "towner-overdue"
    mode: single

  - id: "towner_home_arrival_overdue"
    alias: "Towner: Home arrival overdue warning"
    description: "Warn if Towner hasn't arrived home within 20 minutes"
    trigger:
      - platform: state
        entity_id: input_boolean.towner_expecting_home_arrival
        to: "on"
        for: "00:20:00"
    action:
      - service: notify.all_mobile_devices
        data:
          title: "Towner — Home Arrival Overdue"
          message: "Towner left school 20+ minutes ago but hasn't arrived home yet."
          data:
            tag: "towner-overdue"
    mode: single

  - id: "towner_daily_reset"
    alias: "Towner: Daily state reset"
    description: "Reset all expectation states each morning"
    trigger:
      - platform: time
        at: "06:00:00"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: 
            - input_boolean.towner_expecting_school_arrival
            - input_boolean.towner_expecting_home_arrival
    mode: single
