name: Check
on: [push, pull_request]
jobs:
  home-assistant:
    name: Home Assistant Core Configuration Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out configuration from GitHub
        uses: actions/checkout@v3
        
      - name: Prepare test environment
        run: |
          # Create dummy SERVICE_ACCOUNT.json file with required fields
          echo '{
            "type": "service_account",
            "project_id": "dummy-project-id",
            "private_key_id": "dummy_key_id",
            "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEDummy\n-----END PRIVATE KEY-----\n",
            "client_email": "dummy@dummy-project-id.iam.gserviceaccount.com",
            "client_id": "000000000000000000000",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/dummy.iam.gserviceaccount.com"
          }' > SERVICE_ACCOUNT.json
          
          # Create any other required files/directories
          mkdir -p .storage
      
      - name: Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@v1.4.1
        with:
          version: stable
        continue-on-error: true  # Continue even if there are expected errors
