name: Check
on: [push, pull_request]
jobs:
  home-assistant:
    name: Home Assistant Core Configuratin Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out configuration from GitHub
        uses: actions/checkout@v3
      - name: Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@v1
        with:
          path: "./"
          secrets: fakesecrets.yaml
          version: stable
